{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuerName }}
spec:
  acme:
    email: {{ .Values.certManager.email }}
    server: {{ .Values.certManager.server }}
    privateKeySecretRef:
      name: {{ .Values.certManager.issuerName }}-cluster-issuer
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.ingress.className }}
{{- end }}
