apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: {{ .Values.django.port }}
      targetPort: {{ .Values.django.port }}
  type: ClusterIP