apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secrets
type: Opaque
data:
  postgres-user: {{ .Values.postgresql.user | b64enc }}
  postgres-password: {{ .Values.postgresql.password | b64enc }}