name: Lint Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (lint)
        run: ct lint --target-branch main --check-version-increment=false --validate-maintainers=false

      - name: Run helm lint
        run: |
          find charts -type f -name "Chart.yaml" -print0 | while IFS= read -r -d $'\0' chart; do
            dir=$(dirname "$chart")
            echo "Linting $dir"
            helm lint "$dir"
            helm template "$dir" > /dev/null # Validate templates can render
          done

  call-release:
    needs: lint
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true)
    uses: ./.github/workflows/release.yaml